### ISSUE TITLE
New column: Avg Rating

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#33]
Create a new column avg rating and give rating on the basis of avg ratings fetched from from Google Places.

If rating is not found, assign 3.5

**Comment by rohitmanglik** [comment]
Rating is inconsistent.

e.g. sample.csv-> record 27 (NIIT)  has 4 ratings (5,5,5,4) and still the average rating is 3.5
same case is with record 22 (Arena Animation) and so on.

If the problem is in our code: we can easily fix it.
If data of Google Places is inconsistent - we have to write code to calculate average rating.

**Comment by shashwat-vik** [comment]
Data of Google Places is inconsistent, because in some cases there are Ratings made by people, but there is no Aggregate Rating key in the json response. 
Check that on this [link](https://www.google.co.in/maps/place/NIIT/@27.4876295,77.679584,17z/data=!4m5!3m4!1s0x3973713c1ff18e5b:0x9e3206e5ebace6f8!8m2!3d27.4876295!4d77.6817727?hl=en)
.

So I will be modifying the code to calculate aggregate when there is no aggregate rating.

**Comment by shubhiD** [comment]
Verified, I suppose issue can be closed

**Comment by rohitmanglik** [comment]
I just view the output, it shows aggregate rating when we have individual rating, which is good.

However, when Google doesn't have individual rating but it has aggregate rating, we are assigning a default value  (i.e. 3.5) to aggregate rating. Make necessary changes in code to put aggregate rating in the code.
