### ISSUE TITLE
Errors in Mumbai .csv

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#59]
Traceback (most recent call last):
		  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 353, in processAll
			node = self.searchPlace(row,state)
		  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 208, in searchPlace
			query = row['Name'] + ', ' + row['Locality']
		UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
		^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%^M56%10/19/2016 11:27:43 AM ERROR: Error loading information from facebook for Bharati Vidyapeeth’s Institute of Management Studies & Research
		Traceback (most recent call last):
		  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 353, in processAll
			node = self.searchPlace(row,state)
		  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 208, in searchPlace
			query = row['Name'] + ', ' + row['Locality']
		UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 18: ordinal not in range(128)
		^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M57%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M58%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M59%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M60%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M61%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M62%^M63%^M63%^M63%^M63%^M63%^M63%^M63%^M63%^M63%^M63%10/19/2016 11:28:27 AM ERROR: Error loading information from facebook for IBS – Business School
		Traceback (most recent call last):
		  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 353, in processAll
			node = self.searchPlace(row,state)
		  File "/home/bitnami/rohit/scrap-preprocessor/fbGraph.py", line 208, in searchPlace
			query = row['Name'] + ', ' + row['Locality']
		UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
		@

**Comment by rohitmanglik** [comment]
Bad characters 
	noslist1 [u'8898542258']
	[u'8898542258']
	^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%Bad Phone number +91-22-9892833691
	^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M0%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M1%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%Bad Phone number +91-22620661
	^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M2%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%Bad Phone number +91-22022549
	Bad Phone number +91-22041451
	Bad Phone number +9122045072
	^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M3%^M4%^M4%^M4%^M4%^M4%Bad Phone number +91-22-6681234
	^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M4%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%Bad Phone number +91-26660548
	^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M5%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%Bad Phone number +91-<<->>
	^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M6%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M7%Bad Phone number +9122045072
	^M7%^M7%^M7%^M7%^M7%^M7%^M7%^M8%^M8%^M8%^M8%^M8%Bad Phone number +91-268306279.005.00
	^M8%^M8%^M8%^M8%^M8%Bad Phone number +91-<<->>
	^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M8%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M9%^M10%^M10%^M10%^M10%^M10%^M10%^M10%Bad Phone number +91-<<->>
	^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M10%^M11%^M11%Bad Phone number +91-22-28
	^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%^M11%Bad Phone number +91-6-+91.22.5691.4407
	Bad Phone number +91--+91.22.5691.4405
	^M11%^M11%^M11%^M11%^M11%^M11%Bad Phone number +91-268306279.005.00
	^M12%^M12%^M12%^M12%Bad Phone number +91-22620661
	^M12%^M12%^M12%^M12%^M12%^M12%^M12%^M12%^M12%Bad Phone number +91-228582090
	Bad Phone number +91-22284720
	Bad Phone number +91-22284790

**Comment by rohitmanglik** [comment]
Traceback (most recent call last):
	  File "geocodertest.py", line 243, in <module>
		f.process()
	  File "geocodertest.py", line 70, in process
		self.wikipedia.processAll(self.rows)
	  File "/home/bitnami/rohit/scrap-preprocessor/mediaWiki.py", line 65, in processAll
		page = self.getPage(row)
	  File "/home/bitnami/rohit/scrap-preprocessor/mediaWiki.py", line 22, in getPage
		results = wikipedia.search(name+" "+row['City'],results=5)
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)

**Comment by rohitmanglik** [comment]
/usr/local/lib/python2.7/dist-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

	To get rid of this warning, change this:

	 BeautifulSoup([your markup])

	to this:

	 BeautifulSoup([your markup], "lxml")

	  markup_type=markup_type))

**Comment by rohitmanglik** [comment]
@gupta-shantanu, @shubhiD will be unavailable till Monday so you have to see it yourself.

**Comment by shashwat-vik** [comment]
@gupta-shantanu . Using unicode() is still giving the 'UnicodeDecodeErrors' in fbGraph.py.

```
row['Name'] = unicode(row['Name'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
```

This is because python will implicitly use 'ascii' (default encoding) to decode first and then encode to Unicode.

-----------------------

**Reason for 'UnicodeDecodeErrors'.**

Firstly some row['Name'] have Unicode characters in csv.
This isn't a problem because the file is directly being read as ByteString, so python wont perform any implicit decoding or encoding.

But the situation becomes unsafe due to steps in the function '_googleUpdates()' under autoComplete.py.
Here some existing row field (not the externally added ones), are overwritten by responses from JSON, that are UnicodeString.
So we get a combination of ByteString and UnicodeString.

Now during the steps like  : **row['Name'] + ', ' + row['Locality']**
Python tries to converts Byte to Unicode (if both happen to exist simultaneously), by first implictly decoding it to 'ascii' (default is 'ascii' in Python 2), and then encoding it to Unicode.

This works in some cases when Unicode Characters are in the ascii subset.
But when it is not, like in the Name of institute on row 1452 in scrap4_mumbai, such cases create error during the implicit Decoding phase mentioned above. Reason for UnicodeDecodeError.

So I am explicitly decoding over the implicit one.
Commit 3568908c8ce689b780c369694cf3de6628be13e3 fixes the errors only in fbGraph.py as I clearly know the flow here.

@gupta-shantanu make similar changes in mediaWiki.py depending on your flow there.

**Comment by rohitmanglik** [comment]
@shashwat-vik in your latest testing did you get any warning? 

Currently, if the errors are only pertaining to another wilipedia, let's move the milestone.

**Comment by shashwat-vik** [comment]
With wikipedia module commented, no errors encountered.
So closing the issue.
